### ISSUE TITLE
Create a `.env` file for storing secrets

### ISSUE THREAD

**Issue by Devansh3712** [diragb/pepper-backend#1]
Secrets like the MongoDB URI are present in the `index.js` file and can be accessed by anyone. It is preferred to create a `.env` file for storing such variables.

**Comment by diragb** [comment]
Thanks for the catch!
This repo is just for a quick demo, so I didn't add in a `.env` even though I previously installed `dotenv` - although not adding it is definitely bad practice, I'll be dropping the database inside 48 hours. Hopefully I don't get pwned until then!
